server:
  port: 9090

spring:
  application:
    name: CloudGateway
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id: ProductService
          uri: lb://ProductService
          predicates:
            - Path=/v1/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: productServiceCircuitBreaker
                fallbackUri: forward:/product-fallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity : 1
        - id: OrderService
          uri: lb://OrderService
          predicates:
            - Path=/v1/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderServiceCircuitBreaker
                fallbackUri: forward:/order-fallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: PaymentService
          uri: lb://PaymentService
          predicates:
            - Path=/v1/payments/**
          filters:
            - name: CircuitBreaker
              args:
                name: paymentServiceCircuitBreaker
                fallbackUri: forward:/payment-fallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
management:
  endpoints:
    web:
      exposure:
        include: '*'

